### ISSUE TITLE
.on().subscribe() working for you?

### ISSUE THREAD

**Issue by spencercap** [ftonato/vue-supabase-microblog#4]
hey @ftonato  👋
thanks so much for these repos and the accompanying blog posts! 

i pulled this code, made my own supabase db and updated the config accordingly only to find that realtime updates via `.on().subscribe()` were not triggered as shown off in your GIF. i am able to read the posts once on first load, but nothing after that. are the realtime subscription changes still working for you? or is there some special setting i need to flip in supabase for my database table to be used in realtime? 
cheers!

**Comment by spencercap** [comment]
ah! for myself + future devs -- there is a magic switch on the supabase side (and perhaps you might want to add this to your blog post @ftonato).

navigate to the database tab, then Replication section, then under Sources click the "X tables" (mine was 0 tables), then enable specific or all tables to replicate to realtime.

<img width="1257" alt="Screen Shot 2022-02-25 at 11 06 34 PM" src="https://user-images.githubusercontent.com/4987509/155833787-8bedf368-7732-4dd5-b127-5a409275f499.png">
<img width="1275" alt="Screen Shot 2022-02-25 at 11 07 08 PM" src="https://user-images.githubusercontent.com/4987509/155833790-5bea2727-b3b4-44fb-b3d6-1179c9c1d5d6.png">

**Comment by ftonato** [comment]
Hello @spencercap, thank you very much for the suggestion, I will update both the code and the article (as it was written in the middle of last year some things are already outdated, anyway I will update it for sure).

Again, thanks for the tip 🚀
